shallow_clone: false
skip_branch_with_pr: true
clone_depth: 1

# mostly copied from
environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\tools\\run_with_env.cmd"
    PYPI_REPOSITORY: https://test.pypi.org/legacy/
    PYPI_USERNAME: __token__
    PYPI_PASSWORD:
      secure: "\
        SX9+AI3l3dlYv0NeTnjw8WS+HUHmFJEp+cklKNGx2H7jLtl+0eJxPFf0zCkiW26R0ErtIt\
        ii6xpLbkFzmXBlr6tvE8q7b7FnWcB9vln+wn/Jy9d42QJa2CSAObgQzFo7/HSFq2anLGdv\
        /WTbZ8lZDyJYLaYTCGDRIZ8LTr8HCntQikGMC7UihcqlKT5+dBL/YHeTO3GvtmumaFI5jV\
        jH4mSL4Ki2JMGTzuWjgtazYUb/ShHOg5GfuKuSXuUprRIIc34/NEVHlc4CxdTtN0pOoEH2\
        E+ykDsDxhcJgrBbY6EA="

  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: 32
    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: 64
    - PYTHON: "C:\\Python38"
      PYTHON_VERSION: "3.8.x"
      PYTHON_ARCH: 32
    - PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8.x"
      PYTHON_ARCH: 64
    - PYTHON: "C:\\Python37"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: 32
    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: 64
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: 32
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: 64
    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: 32
    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: 64
matrix:
  fast_finish: true

cache:
  - C:\Users\appveyor\AppData\Local\pip\Cache

install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ECHO "Filesystem root:"
  - ps: "ls \"C:/\""

  - ECHO "Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date. Install wheel package separate so that
  # we also cache wheels
  - python -m pip install --upgrade pip wheel
  - pip install --upgrade setuptools cython -r test-requirements.txt

build_script:
  # Build the compiled extension
  - "%CMD_IN_ENV% python setup.py bdist_wheel --zmq=bundled"
  - ps: "ls dist"
  - forfiles /p dist /m *.whl /c "cmd /c pip install @path"

test_script:
  # Run the project tests
  - cd dist
  - python -c "import zmq; print(zmq.zmq_version())"
  # ``test_win32_shim`` will create a CTLR-C event which will be sent
  # to all processes that share the same group id and creates problems
  # with the appveyor build. To avoid the problems we single out that
  # specific test run it using the ``start`` command and then check
  # the junit report to pass or fail the build.
  - pytest -vsx -m "not new_console" --pyargs zmq.tests
  - start /W pytest -vsx -m "new_console" --pyargs zmq.tests --junit-xml=../results.xml
  - python ../tools/check_junit_result.py ../results.xml
  - cd ..

after_test:
  # If tests are successful, create binary packages for the project.
  - ps: ls dist
  # Upload whl files if building a tag on master branch. The latest Python 3
  # is specified here because twine doesn't support older versions.
  - >
    IF "%APPVEYOR_REPO_TAG%" == "true"
    (
    py -3 -m pip install twine &&
    py -3 -m twine upload --verbose --skip-existing --repository-url %PYPI_REPOSITORY% -u %PYPI_USERNAME% -p %PYPI_PASSWORD% dist/*.whl
    )

artifacts:
  # Archive the generated packages in the ci.appveyor.com build report.
  - path: dist\*

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
